### PR TITLE
Add script! macro

### LINKED ISSUE #11: Implement script! macro
See #4

### PR DESCRIPTION
**Pull request by LeoNero**
Closes #11 

Should be merged after #12.

### CODE REVIEW

**Comment by evaporei** [comment]
I think the main tip I can give here is to maybe use `syn::Error` instead of `panic`s like I've said on your other `Script` PR, other than that great job 👏 

It took me too long to actually be able to use procedural macros in Rust, congratulations 🎉

**Comment by LeoNero** [comment]
Thank you!! <3 you are a Rust godddd

I did not use `syn` here... so I think it would be better to leave it as is? This proc is just to make life a bit easier when creating some tests :P a later refactor would improve error handling.

**Review by evaporei — APPROVED** [review]
I'm no Rust god hahahaha

Just a regular rustacean giving bad opinions 👯

**Comment by LeoNero** [comment]
haha I don't think they are bad, they are helping me a lot :D

**Pull request merged**
